import { getPokemonMove } from "../pokemon-move.registry.js";

import type { PokemonInstanceMove, PokemonMove } from "../pokemon.types.js";

import { POKEMON_STRUGGLE_MOVE_ID } from "./pokemon-battle-command.js";

import {
  getActiveBattlePokemon,
  getBattleParticipantById,
  getOpposingBattleParticipant,
} from "./pokemon-battle-participant.js";

import { isBattleActive } from "./pokemon-battle-lifecycle.js";

import type { BattleTurnResolutionEntry } from "./pokemon-battle-turn-order.js";

import type {
  BattleId,
  BattleInstance,
  BattleParticipantId,
  BattlePokemonState,
} from "./pokemon-battle.types.js";

export interface BattleMoveExecutionContext {
  readonly battleId: BattleId;
  readonly actorParticipantId: BattleParticipantId;
  readonly targetParticipantId: BattleParticipantId;
  readonly actorPokemon: BattlePokemonState;
  readonly targetPokemon: BattlePokemonState;
  readonly selectedMove: PokemonInstanceMove;
  readonly move: PokemonMove;
}

export function createBattleMoveExecutionContext(
  battle: BattleInstance,
  entry: BattleTurnResolutionEntry
): BattleMoveExecutionContext {
  //
  // 1. Battle must still be active.
  //

  if (!isBattleActive(battle)) {
    throw new Error(
      `Cannot create move execution context for battle "${battle.battleId}" with status "${battle.status}"`
    );
  }

  //
  // 2. Command must belong to this Battle.
  //

  if (entry.command.battleId !== battle.battleId) {
    throw new Error(
      `Battle command "${entry.command.battleId}" does not belong to battle "${battle.battleId}"`
    );
  }

  //
  // 3. Resolve actor.
  //

  const actorParticipant = getBattleParticipantById(
    battle,
    entry.command.participantId
  );

  const actorPokemon = getActiveBattlePokemon(actorParticipant);

  //
  // 4. Runtime move execution supports a regular move or the internal
  // Struggle fallback generated by the server when all regular PP is gone.
  //

  if (
    entry.command.action.type !== "use-move" &&
    entry.command.action.type !== "struggle"
  ) {
    throw new Error(
      `Unsupported battle command action while creating move execution context`
    );
  }

  const isStruggle = entry.command.action.type === "struggle";
  const moveId = isStruggle
    ? POKEMON_STRUGGLE_MOVE_ID
    : entry.command.action.moveId;

  //
  // 5. Revalidate the runtime Pokémon move.
  //
  // Regular moves must still exist in the authoritative Pokémon move slots
  // and retain PP at execution time. Struggle is synthetic and intentionally
  // does not mutate the Pokémon's learned move slots.
  //

  const selectedMove: PokemonInstanceMove | undefined = isStruggle
    ? { moveId: POKEMON_STRUGGLE_MOVE_ID, currentPp: 1 }
    : actorPokemon.pokemon.moves.find(
        (candidate) => candidate.moveId === moveId
      );

  if (!selectedMove) {
    throw new Error(
      `Pokémon "${actorPokemon.pokemon.instanceId}" does not know move "${moveId}"`
    );
  }

  if (!isStruggle && selectedMove.currentPp <= 0) {
    throw new Error(`Move "${moveId}" has no PP remaining at execution time`);
  }

  //
  // 6. Resolve static Move definition.
  //

  const move = getPokemonMove(moveId);

  if (!move) {
    throw new Error(
      `Pokémon move "${moveId}" not found while creating battle move execution context`
    );
  }

  //
  // 7. Resolve target.
  //
  // Current Battle foundation is 1v1.
  // Participant type does not define targeting;
  // opposition is resolved exclusively by side.
  //

  const targetParticipant = getOpposingBattleParticipant(
    battle,
    actorParticipant.id
  );

  const targetPokemon = getActiveBattlePokemon(targetParticipant);

  return {
    battleId: battle.battleId,
    actorParticipantId: actorParticipant.id,
    targetParticipantId: targetParticipant.id,
    actorPokemon,
    targetPokemon,
    selectedMove,
    move,
  };
}
