export type CesarAssetDefinition = {
  key: string;
  path: string;
  category: string;
  width: number;
  height: number;
};

export const CESAR_ASSET_LIBRARY: CesarAssetDefinition[] = [
  { key: "cesar-house-01", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-01.png", category: "houses", width: 227, height: 255 },
  { key: "cesar-house-02", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-02.png", category: "houses", width: 232, height: 261 },
  { key: "cesar-house-03", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-03.png", category: "houses", width: 235, height: 255 },
  { key: "cesar-house-04", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-04.png", category: "houses", width: 243, height: 264 },
  { key: "cesar-house-05", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-05.png", category: "houses", width: 216, height: 253 },
  { key: "cesar-house-06", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-06.png", category: "houses", width: 275, height: 257 },
  { key: "cesar-house-07", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-07.png", category: "houses", width: 218, height: 245 },
  { key: "cesar-house-08", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-08.png", category: "houses", width: 227, height: 242 },
  { key: "cesar-house-09", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-09.png", category: "houses", width: 220, height: 245 },
  { key: "cesar-house-10", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-10.png", category: "houses", width: 225, height: 245 },
  { key: "cesar-house-11", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-11.png", category: "houses", width: 228, height: 243 },
  { key: "cesar-house-12", path: "/assets/maps/tilesets/cesar-edition/objects/houses/house-12.png", category: "houses", width: 303, height: 221 },
  { key: "cesar-houses-modular-01", path: "/assets/maps/tilesets/cesar-edition/objects/houses-modular/houses-modular-01.png", category: "houses-modular", width: 585, height: 556 },
  { key: "cesar-houses-modular-02", path: "/assets/maps/tilesets/cesar-edition/objects/houses-modular/houses-modular-02.png", category: "houses-modular", width: 430, height: 558 },
  { key: "cesar-houses-modular-03", path: "/assets/maps/tilesets/cesar-edition/objects/houses-modular/houses-modular-03.png", category: "houses-modular", width: 407, height: 562 },
  { key: "cesar-hospital-red", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/hospital-red.png", category: "special-buildings", width: 380, height: 330 },
  { key: "cesar-shop-blue", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/shop-blue.png", category: "special-buildings", width: 352, height: 328 },
  { key: "cesar-lab-science", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/lab-science.png", category: "special-buildings", width: 351, height: 333 },
  { key: "cesar-gym-rock", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/gym-rock.png", category: "special-buildings", width: 343, height: 322 },
  { key: "cesar-gym-water", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/gym-water.png", category: "special-buildings", width: 438, height: 285 },
  { key: "cesar-gym-fire", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/gym-fire.png", category: "special-buildings", width: 463, height: 289 },
  { key: "cesar-gym-grass", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/gym-grass.png", category: "special-buildings", width: 455, height: 289 },
  { key: "cesar-station", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/station.png", category: "special-buildings", width: 478, height: 317 },
  { key: "cesar-civic-hall", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/civic-hall.png", category: "special-buildings", width: 447, height: 320 },
  { key: "cesar-mansion", path: "/assets/maps/tilesets/cesar-edition/objects/special-buildings/mansion.png", category: "special-buildings", width: 493, height: 317 },
  { key: "cesar-special-icons-signage", path: "/assets/maps/tilesets/cesar-edition/objects/special-modular/special-icons-signage.png", category: "special-modular", width: 1437, height: 115 },
  { key: "cesar-outdoor-props-001", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-001.png", category: "outdoor-props", width: 167, height: 162 },
  { key: "cesar-outdoor-props-002", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-002.png", category: "outdoor-props", width: 134, height: 162 },
  { key: "cesar-outdoor-props-003", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-003.png", category: "outdoor-props", width: 142, height: 162 },
  { key: "cesar-outdoor-props-004", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-004.png", category: "outdoor-props", width: 139, height: 162 },
  { key: "cesar-outdoor-props-005", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-005.png", category: "outdoor-props", width: 153, height: 163 },
  { key: "cesar-outdoor-props-006", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-006.png", category: "outdoor-props", width: 132, height: 164 },
  { key: "cesar-outdoor-props-007", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-007.png", category: "outdoor-props", width: 137, height: 165 },
  { key: "cesar-outdoor-props-008", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-008.png", category: "outdoor-props", width: 312, height: 166 },
  { key: "cesar-outdoor-props-009", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-009.png", category: "outdoor-props", width: 91, height: 120 },
  { key: "cesar-outdoor-props-010", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-010.png", category: "outdoor-props", width: 91, height: 112 },
  { key: "cesar-outdoor-props-011", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-011.png", category: "outdoor-props", width: 92, height: 112 },
  { key: "cesar-outdoor-props-012", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-012.png", category: "outdoor-props", width: 92, height: 112 },
  { key: "cesar-outdoor-props-013", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-013.png", category: "outdoor-props", width: 94, height: 112 },
  { key: "cesar-outdoor-props-014", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-014.png", category: "outdoor-props", width: 93, height: 112 },
  { key: "cesar-outdoor-props-015", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-015.png", category: "outdoor-props", width: 92, height: 112 },
  { key: "cesar-outdoor-props-016", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-016.png", category: "outdoor-props", width: 95, height: 115 },
  { key: "cesar-outdoor-props-017", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-017.png", category: "outdoor-props", width: 131, height: 119 },
  { key: "cesar-outdoor-props-018", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-018.png", category: "outdoor-props", width: 140, height: 113 },
  { key: "cesar-outdoor-props-019", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-019.png", category: "outdoor-props", width: 142, height: 120 },
  { key: "cesar-outdoor-props-020", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-020.png", category: "outdoor-props", width: 141, height: 120 },
  { key: "cesar-outdoor-props-021", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-021.png", category: "outdoor-props", width: 86, height: 134 },
  { key: "cesar-outdoor-props-022", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-022.png", category: "outdoor-props", width: 61, height: 123 },
  { key: "cesar-outdoor-props-023", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-023.png", category: "outdoor-props", width: 68, height: 112 },
  { key: "cesar-outdoor-props-024", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-024.png", category: "outdoor-props", width: 112, height: 127 },
  { key: "cesar-outdoor-props-025", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-025.png", category: "outdoor-props", width: 89, height: 113 },
  { key: "cesar-outdoor-props-026", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-026.png", category: "outdoor-props", width: 55, height: 119 },
  { key: "cesar-outdoor-props-027", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-027.png", category: "outdoor-props", width: 77, height: 122 },
  { key: "cesar-outdoor-props-028", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-028.png", category: "outdoor-props", width: 70, height: 142 },
  { key: "cesar-outdoor-props-029", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-029.png", category: "outdoor-props", width: 65, height: 141 },
  { key: "cesar-outdoor-props-030", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-030.png", category: "outdoor-props", width: 60, height: 133 },
  { key: "cesar-outdoor-props-031", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-031.png", category: "outdoor-props", width: 58, height: 131 },
  { key: "cesar-outdoor-props-032", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-032.png", category: "outdoor-props", width: 73, height: 145 },
  { key: "cesar-outdoor-props-033", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-033.png", category: "outdoor-props", width: 50, height: 138 },
  { key: "cesar-outdoor-props-034", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-034.png", category: "outdoor-props", width: 47, height: 137 },
  { key: "cesar-outdoor-props-035", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-035.png", category: "outdoor-props", width: 108, height: 134 },
  { key: "cesar-outdoor-props-036", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-036.png", category: "outdoor-props", width: 61, height: 142 },
  { key: "cesar-outdoor-props-037", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-037.png", category: "outdoor-props", width: 56, height: 140 },
  { key: "cesar-outdoor-props-038", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-038.png", category: "outdoor-props", width: 849, height: 212 },
  { key: "cesar-outdoor-props-039", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-039.png", category: "outdoor-props", width: 86, height: 212 },
  { key: "cesar-outdoor-props-040", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-040.png", category: "outdoor-props", width: 118, height: 215 },
  { key: "cesar-outdoor-props-041", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-041.png", category: "outdoor-props", width: 45, height: 215 },
  { key: "cesar-outdoor-props-042", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-042.png", category: "outdoor-props", width: 75, height: 215 },
  { key: "cesar-outdoor-props-043", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-043.png", category: "outdoor-props", width: 130, height: 215 },
  { key: "cesar-outdoor-props-044", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-044.png", category: "outdoor-props", width: 89, height: 144 },
  { key: "cesar-outdoor-props-045", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-045.png", category: "outdoor-props", width: 78, height: 133 },
  { key: "cesar-outdoor-props-046", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-046.png", category: "outdoor-props", width: 86, height: 145 },
  { key: "cesar-outdoor-props-047", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-047.png", category: "outdoor-props", width: 104, height: 126 },
  { key: "cesar-outdoor-props-048", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-048.png", category: "outdoor-props", width: 195, height: 150 },
  { key: "cesar-outdoor-props-049", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-049.png", category: "outdoor-props", width: 73, height: 135 },
  { key: "cesar-outdoor-props-050", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-050.png", category: "outdoor-props", width: 98, height: 142 },
  { key: "cesar-outdoor-props-051", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-051.png", category: "outdoor-props", width: 93, height: 86 },
  { key: "cesar-outdoor-props-052", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-052.png", category: "outdoor-props", width: 127, height: 142 },
  { key: "cesar-outdoor-props-053", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-053.png", category: "outdoor-props", width: 99, height: 150 },
  { key: "cesar-outdoor-props-054", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-054.png", category: "outdoor-props", width: 231, height: 150 },
  { key: "cesar-outdoor-props-055", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-055.png", category: "outdoor-props", width: 141, height: 117 },
  { key: "cesar-outdoor-props-056", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-056.png", category: "outdoor-props", width: 130, height: 116 },
  { key: "cesar-outdoor-props-057", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-057.png", category: "outdoor-props", width: 131, height: 116 },
  { key: "cesar-outdoor-props-058", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-058.png", category: "outdoor-props", width: 123, height: 117 },
  { key: "cesar-outdoor-props-059", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-059.png", category: "outdoor-props", width: 134, height: 118 },
  { key: "cesar-outdoor-props-060", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-060.png", category: "outdoor-props", width: 80, height: 113 },
  { key: "cesar-outdoor-props-061", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-061.png", category: "outdoor-props", width: 89, height: 113 },
  { key: "cesar-outdoor-props-062", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-062.png", category: "outdoor-props", width: 136, height: 106 },
  { key: "cesar-outdoor-props-063", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-063.png", category: "outdoor-props", width: 127, height: 110 },
  { key: "cesar-outdoor-props-064", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-064.png", category: "outdoor-props", width: 99, height: 92 },
  { key: "cesar-outdoor-props-065", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-065.png", category: "outdoor-props", width: 128, height: 98 },
  { key: "cesar-outdoor-props-066", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-066.png", category: "outdoor-props", width: 132, height: 82 },
  { key: "cesar-outdoor-props-067", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-067.png", category: "outdoor-props", width: 134, height: 78 },
  { key: "cesar-outdoor-props-068", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-068.png", category: "outdoor-props", width: 134, height: 79 },
  { key: "cesar-outdoor-props-069", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-069.png", category: "outdoor-props", width: 130, height: 78 },
  { key: "cesar-outdoor-props-070", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-070.png", category: "outdoor-props", width: 131, height: 80 },
  { key: "cesar-outdoor-props-071", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-071.png", category: "outdoor-props", width: 50, height: 103 },
  { key: "cesar-outdoor-props-072", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-072.png", category: "outdoor-props", width: 57, height: 91 },
  { key: "cesar-outdoor-props-073", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-073.png", category: "outdoor-props", width: 41, height: 110 },
  { key: "cesar-outdoor-props-074", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-074.png", category: "outdoor-props", width: 45, height: 103 },
  { key: "cesar-outdoor-props-075", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-075.png", category: "outdoor-props", width: 120, height: 97 },
  { key: "cesar-outdoor-props-076", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-076.png", category: "outdoor-props", width: 126, height: 100 },
  { key: "cesar-outdoor-props-077", path: "/assets/maps/tilesets/cesar-edition/objects/outdoor-props/outdoor-props-077.png", category: "outdoor-props", width: 145, height: 102 },
  { key: "cesar-terrain-nature-stamps-001", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-001.png", category: "terrain-nature-stamps", width: 99, height: 203 },
  { key: "cesar-terrain-nature-stamps-002", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-002.png", category: "terrain-nature-stamps", width: 1319, height: 205 },
  { key: "cesar-terrain-nature-stamps-003", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-003.png", category: "terrain-nature-stamps", width: 92, height: 227 },
  { key: "cesar-terrain-nature-stamps-004", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-004.png", category: "terrain-nature-stamps", width: 692, height: 228 },
  { key: "cesar-terrain-nature-stamps-005", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-005.png", category: "terrain-nature-stamps", width: 629, height: 228 },
  { key: "cesar-terrain-nature-stamps-006", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-006.png", category: "terrain-nature-stamps", width: 188, height: 120 },
  { key: "cesar-terrain-nature-stamps-007", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-007.png", category: "terrain-nature-stamps", width: 105, height: 120 },
  { key: "cesar-terrain-nature-stamps-008", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-008.png", category: "terrain-nature-stamps", width: 260, height: 120 },
  { key: "cesar-terrain-nature-stamps-009", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-009.png", category: "terrain-nature-stamps", width: 97, height: 120 },
  { key: "cesar-terrain-nature-stamps-010", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-010.png", category: "terrain-nature-stamps", width: 67, height: 116 },
  { key: "cesar-terrain-nature-stamps-011", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-011.png", category: "terrain-nature-stamps", width: 182, height: 118 },
  { key: "cesar-terrain-nature-stamps-012", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-012.png", category: "terrain-nature-stamps", width: 160, height: 118 },
  { key: "cesar-terrain-nature-stamps-013", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-013.png", category: "terrain-nature-stamps", width: 59, height: 117 },
  { key: "cesar-terrain-nature-stamps-014", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-014.png", category: "terrain-nature-stamps", width: 145, height: 116 },
  { key: "cesar-terrain-nature-stamps-015", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-015.png", category: "terrain-nature-stamps", width: 79, height: 119 },
  { key: "cesar-terrain-nature-stamps-016", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-016.png", category: "terrain-nature-stamps", width: 1420, height: 216 },
  { key: "cesar-terrain-nature-stamps-017", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-017.png", category: "terrain-nature-stamps", width: 301, height: 169 },
  { key: "cesar-terrain-nature-stamps-018", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-018.png", category: "terrain-nature-stamps", width: 1118, height: 170 },
  { key: "cesar-terrain-nature-stamps-019", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-019.png", category: "terrain-nature-stamps", width: 79, height: 124 },
  { key: "cesar-terrain-nature-stamps-020", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-020.png", category: "terrain-nature-stamps", width: 1269, height: 124 },
  { key: "cesar-terrain-nature-stamps-021", path: "/assets/maps/tilesets/cesar-edition/objects/terrain-nature-stamps/terrain-nature-stamps-021.png", category: "terrain-nature-stamps", width: 59, height: 124 },
];

export function preloadCesarAssetLibrary(scene: Phaser.Scene): void {
  for (const asset of CESAR_ASSET_LIBRARY) {
    if (!scene.textures.exists(asset.key)) {
      scene.load.image(asset.key, asset.path);
    }
  }
}
